### ISSUE TITLE
Upgrade to Scala 2.13

### ISSUE THREAD

**Issue by tzeman77** [sscarduzio/reson#3]
This CR upgrades reson to Scala 2.13.

It should be quite straightforward by updating the dependencies (`finagle` 6.33 -> 21.x). Unfortunately, the `rapture` project does not support scala 2.13, therefore I suggest to switch json lib to `json4s` using `jackson` as backend implementation (jackson is pulled as dependency by finagle anyway).

Is that acceptable?

I can implement this CR.

**Comment by sscarduzio** [comment]
Hi @tzeman77 I'd be delighted to review and merge this change request 👍
